using UnityEngine;

namespace Marte.World
{
    // Generated by Marte/Terrain/Import Jezero. Positions are "true" map coordinates with the origin at the map center.
    public class JezeroWorldInfo : ScriptableObject
    {
        public int tilesX;
        public int tilesZ;
        public float tileSize = 1000f;
        public float terrainHeight;
        public string tilesResourceFolder = "Terrain/Jezero";

        [Header("Horizon (whole map, low resolution)")]
        public string horizonResource = "Terrain/JezeroHorizon";
        public int horizonStep = 32;
        public Material horizonMaterial;

        [Header("Backdrop (visual only, beyond the playable map)")]
        public string backdropResource = "Terrain/JezeroBackdrop";
        public int backdropSamples;
        public float backdropSpacing;
        public float backdropHalfExtent;
        public float backdropBaseY;          // world y of encoded value 0
        public float backdropHeightScale;    // world metres per encoded step

        [Header("Gameplay")]
        public float waterY;
        public Vector3 start;
        public float startYaw;
        [Tooltip("Where the player may walk (x, z from the map center). Beyond it the world is visual only.")]
        public Vector2[] playableArea;

        [Tooltip("Named places from ferramentas/terreno/marcos.json (D15/D16), positioned on the imported terrain.")]
        public Landmark[] landmarks;

        public float HalfX => tilesX * tileSize / 2f;
        public float HalfZ => tilesZ * tileSize / 2f;
        public int HorizonSizeX => tilesX * horizonStep + 1;
        public int HorizonSizeZ => tilesZ * horizonStep + 1;

        public Vector3 TileOrigin(int x, int z) => new Vector3(x * tileSize - HalfX, 0f, z * tileSize - HalfZ);
        public string TileResource(int x, int z) => $"{tilesResourceFolder}/Jezero_{x}_{z}";
    }
}
